# Generated by Django 2.1.7 on 2019-04-16 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('machine_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('vocation', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('machine_num', models.IntegerField(default=0)),
                ('charger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Charger')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Room'),
        ),
    ]
