# Generated by Django 2.1.7 on 2019-04-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190425_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collective',
            name='machines',
        ),
        migrations.AddField(
            model_name='collective',
            name='machines',
            field=models.ManyToManyField(to='api.Client'),
        ),
    ]
