# Generated by Django 2.1.7 on 2019-04-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190427_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='warehouse_type',
            field=models.IntegerField(blank=True, choices=[(1, 'SVN'), (2, 'Git')], null=True),
        ),
    ]
