# Generated by Django 2.1.7 on 2019-04-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_warehouse_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32)),
                ('ssh', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('ps', models.CharField(max_length=1024)),
            ],
        ),
    ]
