# Generated by Django 2.1.7 on 2019-04-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_authcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcenter',
            name='ps',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
