# Generated by Django 2.1.7 on 2019-04-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190428_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_amount', models.IntegerField()),
                ('interval_measure', models.CharField(max_length=32)),
            ],
        ),
    ]
