# Generated by Django 2.1.7 on 2019-04-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.CharField(max_length=32)),
                ('hour', models.CharField(max_length=32)),
                ('day_week', models.CharField(max_length=32)),
                ('day_month', models.CharField(max_length=32)),
                ('month_year', models.CharField(max_length=32)),
            ],
        ),
    ]
