# Generated by Django 2.1.7 on 2019-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cxfb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxfb',
            name='if_clean',
            field=models.CharField(blank=True, default='0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cxfb',
            name='if_local',
            field=models.CharField(blank=True, default='0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cxfb',
            name='shell',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
