# Generated by Django 2.1.7 on 2019-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190506_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxfb',
            name='status',
            field=models.CharField(blank=True, default='未部署', max_length=32, null=True),
        ),
    ]
