# Generated by Django 2.1.7 on 2019-04-16 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ip', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=64)),
                ('cpu_model', models.CharField(max_length=64)),
                ('cpu_num', models.IntegerField()),
                ('memory', models.CharField(max_length=32)),
                ('disk', models.CharField(max_length=32)),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Cabinet')),
            ],
        ),
    ]
