# Generated by Django 2.1.7 on 2019-04-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ip', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=64)),
                ('cpu_model', models.CharField(max_length=64)),
                ('cpu_num', models.IntegerField()),
                ('memory', models.CharField(max_length=32)),
                ('disk', models.CharField(max_length=32)),
                ('system', models.CharField(max_length=32)),
                ('root', models.CharField(default='root', max_length=32)),
                ('password', models.CharField(default='123456', max_length=32)),
            ],
        ),
    ]
